#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.135                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC =  -Idep
CFLAGS =  -std=c++11 -Wextra -Wall
RESINC = 
LIBDIR =  -Llib
LIB = 
LDFLAGS =  -lmingw32 -lSDL2main -lSDL2 -lSDL2_image

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -ansi -pg -g
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  $(LDFLAGS) -pg -lgmon
OBJDIR_DEBUG = obj\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\Debug\Star-Pusher.exe

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O2
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj\Release
DEP_RELEASE = 
OUT_RELEASE = bin\Release\Star-Pusher.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\src\main.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\src\main.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\Debug md bin\Debug
	cmd /c if not exist $(OBJDIR_DEBUG)\src md $(OBJDIR_DEBUG)\src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIB_DEBUG) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJDIR_DEBUG)\src\main.o $(LDFLAGS_DEBUG) 
#	$(LD) $(LDFLAGS_DEBUG) $(LIBDIR_DEBUG) $(OBJ_DEBUG) $(LIB_DEBUG) -o $(OUT_DEBUG)

$(OBJDIR_DEBUG)\src\main.o: src\main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\main.cpp -o $(OBJDIR_DEBUG)\src\main.o

clean_debug: 
	cmd /c if exist $(OBJ_DEBUG) del /f $(OBJ_DEBUG)
	cmd /c if exist $(OUT_DEBUG) del /f $(OUT_DEBUG)
# Don't want to remove dll file
#	cmd /c rd bin\Debug
	cmd /c if exist $(OBJDIR_DEBUG)\src rd $(OBJDIR_DEBUG)\src

before_release: 
	cmd /c if not exist bin\Release md bin\Release
	cmd /c if not exist $(OBJDIR_RELEASE)\src md $(OBJDIR_RELEASE)\src

after_release: 

release: before_release out_release after_release

out_release: $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LDFLAGS_RELEASE) $(LIBDIR_RELEASE) $(OBJ_RELEASE) $(LIB_RELEASE) -o $(OUT_RELEASE)

$(OBJDIR_RELEASE)\src\main.o: src\main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\main.cpp -o $(OBJDIR_RELEASE)\src\main.o

clean_release: 
	cmd /c if exist $(OBJ_RELEASE) del /f $(OBJ_RELEASE)
	cmd /c if exist $(OUT_RELEASE) del /f $(OUT_RELEASE)
# Don't want to remove dll
#	cmd /c rd bin\Release
	cmd /c if exist $(OBJDIR_RELEASE)\src rd $(OBJDIR_RELEASE)\src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

